### ISSUE TITLE
500 - Inernal server error

### ISSUE THREAD

**Issue by kmintech** [magespecialist/m2-MSP_CashOnDelivery#17] opened 2017-01-10 11:58 UTC
Hi,
I have facing issue while using this module M2:- 
Steps are here on checkout page
1. Login in account on checkout page or can place order as guest user
2. select shipping method
3. select payment method
4. Again try to change shipping method get 500 Internal server error when system is trying to fetch selected payment method and page loader is continuously moving. This error will not see directly, we can see it thought firebug or by inspect element.
Url - http://192.169.182.188/~gbdemoin/
![500-internal-server-error](https://cloud.githubusercontent.com/assets/25031143/21805415/11f1bd84-d75a-11e6-96b8-c87d2528ec11.png)

**Comment by ebaschiera** [comment] 2017-01-22 14:59
Did you check the PHP error log file? Everytime a 500 error occurs, PHP logs a fatal error on its log file.

**Comment by phoenix128** [comment] 2017-02-02 13:20
Did you upgrade to last module version? This should have been already solved.

**Comment by kmintech** [comment] 2017-02-02 13:36
No, Will update it tomorrow and will update accordingly THANKS :)

**Comment by kmintech** [comment] 2017-02-08 07:03
Hi,

I have updated latest one, But getting same error.

I have already sent the test cases in my previous email. You can try that on my demo site.

"{"message":"Property \"Title\" does not have corresponding setter in class \"Magento\\Quote\\Api\\Data
\\PaymentInterface\".","trace":"#0 \/var\/www\/html\/goofybuy\/vendor\/magento\/framework\/Reflection
\/NameFinder.php(59): Magento\\Framework\\Reflection\\NameFinder->findAccessorMethodName(Object(Zend
\\Code\\Reflection\\ClassReflection), 'Title', 'getTitle', 'isTitle')\n#1 \/var\/www\/html\/goofybuy
\/vendor\/magento\/framework\/Webapi\/ServiceInputProcessor.php(158): Magento\\Framework\\Reflection
\\NameFinder->getGetterMethodName(Object(Zend\\Code\\Reflection\\ClassReflection), 'Title')\n#2 \/var
\/www\/html\/goofybuy\/vendor\/magento\/framework\/Webapi\/ServiceInputProcessor.php(322): Magento\\Framework
\\Webapi\\ServiceInputProcessor->_createFromArray('Magento\\\\Quote\\\\A...', Array)\n#3 \/var\/www\
/html\/goofybuy\/vendor\/magento\/framework\/Webapi\/ServiceInputProcessor.php(119): Magento\\Framework
\\Webapi\\ServiceInputProcessor->convertValue(Array, 'Magento\\\\Quote\\\\A...')\n#4 \/var\/www\/html
\/goofybuy\/vendor\/magento\/module-webapi\/Controller\/Rest\/InputParamsResolver.php(101): Magento\
\Framework\\Webapi\\ServiceInputProcessor->process('Magento\\\\Quote\\\\A...', 'set', Array)\n#5 \/var
\/www\/html\/goofybuy\/vendor\/magento\/module-webapi\/Controller\/Rest.php(299): Magento\\Webapi\\Controller
\\Rest\\InputParamsResolver->resolve()\n#6 \/var\/www\/html\/goofybuy\/vendor\/magento\/module-webapi
\/Controller\/Rest.php(216): Magento\\Webapi\\Controller\\Rest->processApiRequest()\n#7 \/var\/www\/html
\/goofybuy\/vendor\/magento\/framework\/Interception\/Interceptor.php(74): Magento\\Webapi\\Controller
\\Rest->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#8 \/var\/www\/html\/goofybuy\/vendor
\/magento\/framework\/Interception\/Chain\/Chain.php(70): Magento\\Webapi\\Controller\\Rest\\Interceptor-
>___callParent('dispatch', Array)\n#9 \/var\/www\/html\/goofybuy\/vendor\/magento\/framework\/Interception
\/Interceptor.php(138): Magento\\Framework\\Interception\\Chain\\Chain->invokeNext('Magento\\\\Webapi
\\\\...', 'dispatch', Object(Magento\\Webapi\\Controller\\Rest\\Interceptor), Array, 'infortis_cgen_m
...')\n#10 \/var\/www\/html\/goofybuy\/app\/code\/Infortis\/Cgen\/Plugin\/Magento\/Framework\/App\/FrontController
.php(32): Magento\\Webapi\\Controller\\Rest\\Interceptor->Magento\\Framework\\Interception\\{closure
}(Object(Magento\\Framework\\App\\Request\\Http))\n#11 \/var\/www\/html\/goofybuy\/vendor\/magento\/framework
\/Interception\/Interceptor.php(142): Infortis\\Cgen\\Plugin\\Magento\\Framework\\App\\FrontController-
>aroundDispatch(Object(Magento\\Webapi\\Controller\\Rest\\Interceptor), Object(Closure), Object(Magento
\\Framework\\App\\Request\\Http))\n#12 \/var\/www\/html\/goofybuy\/var\/generation\/Magento\/Webapi\
/Controller\/Rest\/Interceptor.php(39): Magento\\Webapi\\Controller\\Rest\\Interceptor->___callPlugins
('dispatch', Array, Array)\n#13 \/var\/www\/html\/goofybuy\/vendor\/magento\/framework\/App\/Http.php
(135): Magento\\Webapi\\Controller\\Rest\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request
\\Http))\n#14 \/var\/www\/html\/goofybuy\/vendor\/magento\/framework\/App\/Bootstrap.php(258): Magento
\\Framework\\App\\Http->launch()\n#15 \/var\/www\/html\/goofybuy\/index.php(42): Magento\\Framework\
\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http))\n#16 {main}"}"

Regards
Sonu

**Comment by phoenix128** [comment] 2017-02-22 16:58
Are you using a custom checkout module?

**Comment by kmintech** [comment] 2017-02-23 05:45
Yes. I am using - https://www.iwdagency.com/extensions/one-step-page-checkout.html free version.
But also i checked by disable custom checkout module. There are same issue.

**Comment by zajazdowicz** [comment] 2017-03-16 12:57
We have the same issue, it doesn't matter if we use custom checkout (like here in attachment) or the one from magento core. I think the issue is related to postal code field, when we put some specific postal code (for example 42-216) then it won't work. 
![image](https://cloud.githubusercontent.com/assets/25529336/23997127/6a0fb63c-0a50-11e7-9d46-bead264365f4.png)

**Comment by phoenix128** [comment] 2017-03-18 20:34
Thank you for reporting, we are moving this issue to max priority.

**Comment by zajazdowicz** [comment] 2017-03-22 08:09
Problem is somewhere here - me.refreshMethod();
when i comment this line here - vendor/msp/cashondelivery/view/frontend/web/js/view/payment/method-renderer/cashondelivery.js, module will work, it just won't show additional fee on checkout.

**Comment by phoenix128** [comment] 2017-03-22 15:25
@zajazdowicz , yes, we also found it.

**Comment by phoenix128** [comment] 2017-03-22 16:27
There is something that does not match with your scenario. What is your Magento version?

**Comment by zajazdowicz** [comment] 2017-03-23 07:21
Currently we're using 2.1.5 and One step checkout from Mageplaza. We had this problem on 2.1.3 too.

**Comment by phoenix128** [comment] 2017-03-24 15:45
We finally found it and fixed in 1.1.3

**Closed as completed by phoenix128** 2017-03-24 15:45 UTC

**Comment by kmintech** [comment] 2017-03-27 07:39
thanks buddy, now working fine
